"""User model token field added

Revision ID: 85125576b291
Revises: 964b69cd6ace
Create Date: 2021-05-09 19:44:14.149909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85125576b291'
down_revision = '964b69cd6ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
