"""User model user_id unique key applied

Revision ID: 964b69cd6ace
Revises: 040ee0c17cba
Create Date: 2021-05-09 18:10:04.712186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964b69cd6ace'
down_revision = '040ee0c17cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
